name : Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:  
    branches: [main, master]
jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run:  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm install
              export DOMAIN=develop.testing.tutorme.dev
              npm test -- wl --runInBand

        
      
