name : Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:  
    branches: [main, master] 
  schedule:
    - cron: '30 5,17 * * *'  
jobs:
  Footer_Test:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Config npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  
      - name: Install NPM
        run:  npm install
              npm audit fix
      - name: select env
        run:  export DOMAIN=stg-tutor.peardeck.com
      - name: Run test
        run:  npm test -- Footer-links.test.ts
